name: Monitor Clima San Isidro

on:
  schedule:
    - cron: '45 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Librerias
        run: pip install pandas requests

      - name: Ejecutar Script
        run: python captura_clima.py

      - name: Subir Archivo
        run: |
          git config --global user.name "ClimaBot"
          git config --global user.email "bot@github.com"
          git add registro_clima_san_isidro.csv
          git commit -m "Captura exitosa $(date)" || exit 0
          git push origin main
