name: Monitor Clima San Isidro

on:
  schedule:
    - cron: '45 */3 * * *'
  workflow_dispatch:

# Esto le da permiso al robot para escribir archivos en tu repositorio
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar librerias
        run: pip install pandas requests beautifulsoup4

      - name: Ejecutar script de captura
        run: python captura_clima.py

      - name: Guardar cambios
        run: |
          git config --global user.name "ClimaBot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Captura automatica: $(date)" || exit 0
          git push
