name: Monitor Clima San Isidro

on:
  schedule:
    # Corre cada 3 horas (00:00, 03:00, 06:00, etc. en hora UTC)
    # Como Argentina es UTC-3, esto capturará datos a las 21hs, 00hs, 03hs... 
    # y la ejecución de las 02:45 UTC será la de las 23:45 Arg (que activa los gráficos)
    - cron: '45 */3 * * *'
  workflow_dispatch: # Esto nos permite probarlo manualmente ahora mismo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerias
        run: pip install pandas requests beautifulsoup4

      - name: Ejecutar script de captura
        run: python captura_clima.py

      - name: Guardar cambios
        run: |
          git config --global user.name "ClimaBot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Captura automatica: $(date)" || exit 0
          git push
